# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_analysis', to='patient.FoodAnalysis', verbose_name='Cardápio'),
        ),
        migrations.AddField(
            model_name='meal',
            name='original_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_food', to='food.Food', verbose_name='Alimento'),
        ),
    ]
