# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='home_measure',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medida Caseira'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Quantidade'),
        ),
    ]
