# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_foodanalysis'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_analysis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meal_analysis', to='patient.FoodAnalysis', verbose_name='Card\xe1pio'),
            preserve_default=False,
        ),
    ]
