# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição da Tabela')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('path', models.FileField(blank=True, null=True, upload_to='upload/table', verbose_name='Tabela')),
            ],
        ),
    ]
