# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_measure_measure_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunity',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unity_measure', to='food.Measure', verbose_name='Medida'),
        ),
    ]
