# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20171128_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='home_measure',
            field=models.CharField(max_length=255, null=True, verbose_name='Med. Caseira'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('CAFÉ DA MANHÃ', 'Café da Manhã'), ('LANCHE I', 'Lanche I'), ('ALMOÇO', 'Almoço'), ('LANCHE II', 'Lanche II'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], default=None, max_length=40, null=True, verbose_name='Refeição'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='original_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_food', to='food.Food', verbose_name='Alimento'),
        ),
    ]
