# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_meal_food_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='home_measure',
            field=models.CharField(blank=True, choices=[('CAF\xc9 DA MANH\xc3', 'Caf\xe9 da Manh\xe3'), ('LANCHE I', 'Lanche I'), ('ALMO\xc7O', 'Almo\xe7o'), ('LANCHE II', 'Lanche II'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], default=None, max_length=40, null=True, verbose_name='Medida Caseira'),
        ),
    ]
