# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180123_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Quantidade'),
        ),
    ]
