# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_measureunity_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureunity',
            name='measure',
        ),
        migrations.AddField(
            model_name='measure',
            name='measure_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure_unity', to='food.MeasureUnity', verbose_name='Unidade de Medida'),
        ),
    ]
