# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20171031_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='home_measure',
            field=models.CharField(default=None, max_length=255, verbose_name='Med. Caseira'),
            preserve_default=False,
        ),
    ]
