# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20180122_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='measure',
        ),
        migrations.AddField(
            model_name='measure',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure_food', to='food.Food', verbose_name='Alimento'),
        ),
    ]
