# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20180123_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substituteitem',
            name='meal_substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_meal', to='food.MealItem', verbose_name='Refeição'),
        ),
    ]
