# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('message', models.CharField(max_length=200, verbose_name='Mensagem')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_nutritionist', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
            ],
        ),
    ]
