# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidance',
            name='nutritionist',
        ),
        migrations.DeleteModel(
            name='Guidance',
        ),
    ]
