# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maran\xe3o'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PE', 'Pernanbuco'), ('PI', 'Piau\xed'), ('PR', 'Paran\xe1'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'S\xe3o Paulo'), ('TO', 'Tocantins')], default='PI', max_length=2, verbose_name='UF')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=20, verbose_name='N\xfamero')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('reference_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('country', models.CharField(default='Brasil', max_length=255, verbose_name='Pa\xeds')),
            ],
        ),
        migrations.CreateModel(
            name='BodyCircunference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thorax_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do T\xf3rax')),
                ('shoulder_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Ombro')),
                ('relaxed_arm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Bra\xe7o Relaxado')),
                ('contracted_arm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Bra\xe7o Contra\xeddo')),
                ('forearm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Antebra\xe7o')),
                ('waist_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Cintura')),
                ('abdomen_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Abdomen')),
                ('hip_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Quadril')),
                ('proximal_thigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Proximal')),
                ('medial_tigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Medial')),
                ('distal_tigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Distal')),
                ('calf_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Panturrilha')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=255, verbose_name='Objetivo')),
                ('observation', models.CharField(max_length=255, verbose_name='Observa\xe7\xf5es gerais')),
                ('date', models.DateField(verbose_name='Data da consulta')),
                ('family_history', models.CharField(max_length=255, verbose_name='Hist\xf3rico Familiar')),
                ('drugs', models.CharField(max_length=255, verbose_name='F\xe1rmacos')),
                ('life_style', models.CharField(max_length=255, verbose_name='Estilo de vida')),
                ('feed_preferences', models.CharField(max_length=255, verbose_name='Prefer\xeancias Alimentares')),
                ('prognostic', models.CharField(max_length=255, verbose_name='Progn\xf3stico')),
                ('evaluation', models.CharField(max_length=255, verbose_name='Avalia\xe7\xe3o')),
                ('bodycirc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bodycirc', to='patient.BodyCircunference', verbose_name='Circunfer\xeancia Corporal')),
            ],
            options={
                'ordering': ['-patient'],
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='EnergyCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Altura (m)')),
                ('lean_mass', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Massa livre (kg)')),
                ('formula', models.CharField(blank=True, choices=[('HARRIS-BENEDICT(1919)', 'Harris-Benedict(1919)'), ('HARRIS-BENEDICT(1984)', 'Harris-Benedict(1984)'), ('CUNNINGHAN(1996)', 'Cunninghan(1996)')], default=None, max_length=10, null=True, verbose_name='F\xf3rmula')),
                ('calc_title', models.CharField(max_length=255, verbose_name='Fator de Atividade')),
                ('met_method', models.CharField(max_length=255, verbose_name='M\xe9todo MET')),
                ('weight_program', models.CharField(max_length=255, verbose_name='Programa de Peso')),
                ('mbr', models.CharField(max_length=255, verbose_name='Taxa Metab\xf3lica Basal')),
                ('tee', models.CharField(max_length=255, verbose_name='Gasto Energ\xe9tico Total')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descri\xe7\xe3o')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/exam', verbose_name='Exame')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_consultation', to='patient.Consultation', verbose_name='Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('marital_status', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10, null=True, verbose_name='Estado C\xedvil')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('ocupation', models.CharField(max_length=16, verbose_name='Ocupa\xe7\xe3o')),
                ('observation', models.CharField(max_length=200, verbose_name='Observa\xe7\xe3o sobre o paciente')),
                ('ethnicity', models.CharField(blank=True, choices=[('BRANCO', 'Branco'), ('NEGRO', 'Negro'), ('IND\xcdGENA', 'Ind\xedgena'), ('PARDO', 'Pardo'), ('MULATO', 'Mulato'), ('OUTRO', 'Outro')], default=None, max_length=10, null=True, verbose_name='Etnia')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='patient.Address', verbose_name='Endere\xe7o')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_users', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Patology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descri\xe7\xe3o da Patologia')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation', to='patient.Patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_patology', to='patient.Patology', verbose_name='Patologia'),
        ),
    ]
