# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='PI', max_length=2, verbose_name='UF')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('reference_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('country', models.CharField(default='Brasil', max_length=255, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='BodyCircunference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thorax_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Tórax')),
                ('shoulder_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Ombro')),
                ('relaxed_arm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Braço Relaxado')),
                ('contracted_arm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Braço Contraído')),
                ('forearm_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Antebraço')),
                ('waist_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Cintura')),
                ('abdomen_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. do Abdomen')),
                ('hip_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Quadril')),
                ('proximal_thigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Proximal')),
                ('medial_thigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Medial')),
                ('distal_thigh_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Coxa Distal')),
                ('calf_circ', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Circ. Panturrilha')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=255, verbose_name='Objetivo')),
                ('observation', models.CharField(max_length=255, verbose_name='Observações gerais')),
                ('date', models.DateField(verbose_name='Data da consulta')),
                ('family_history', models.CharField(max_length=255, verbose_name='Histórico Familiar')),
                ('drugs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fármacos')),
                ('life_style', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estilo de vida')),
                ('feed_preferences', models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferências Alimentares')),
                ('prognostic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prognóstico')),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avaliação')),
                ('bodycirc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bodycirc', to='patient.BodyCircunference', verbose_name='Circunferência Corporal')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-patient'],
            },
        ),
        migrations.CreateModel(
            name='EnergyCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Cálculo')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Altura (cm)')),
                ('lean_mass', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Massa livre (kg)')),
                ('formula', models.CharField(choices=[('HARRIS-BENEDICT(1919)', 'Harris-Benedict(1919)'), ('HARRIS-BENEDICT(1984)', 'Harris-Benedict(1984)'), ('CUNNINGHAN(1996)', 'Cunninghan(1996)')], default='HARRIS-BENEDICT(1919)', max_length=30, null=True, verbose_name='Fórmula')),
                ('activity_factor', models.CharField(choices=[('1.2', 'Sedentário'), ('1.375', 'Exercício Leve'), ('1.55', 'Exercício Moderado'), ('1.725', 'Exercício Pesado'), ('1.9', 'Exercício Muito Pesado')], default='1.2', max_length=30, null=True, verbose_name='Fator de Atividade')),
                ('mbr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxa Metabólica Basal')),
                ('tee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gasto Energético Total')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('path', models.FileField(blank=True, null=True, upload_to='upload/exam', verbose_name='Exame')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_consultation', to='patient.Consultation', verbose_name='Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('published', models.BooleanField(verbose_name='Publicar?')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_consultation', to='patient.Consultation', verbose_name='Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('marital_status', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10, null=True, verbose_name='Estado Cívil')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('ocupation', models.CharField(max_length=16, verbose_name='Ocupação')),
                ('observation', models.CharField(max_length=200, verbose_name='Observação sobre o paciente')),
                ('ethnicity', models.CharField(choices=[('BRANCO', 'Branco'), ('NEGRO', 'Negro'), ('INDÍGENA', 'Indígena'), ('PARDO', 'Pardo'), ('MULATO', 'Mulato'), ('OUTRO', 'Outro')], default=None, max_length=10, verbose_name='Etnia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='patient.Address', verbose_name='Endereço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_users', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patologia')),
            ],
        ),
        migrations.CreateModel(
            name='SkinFold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_mass', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Massa Corporal (kg)')),
                ('seated_height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Estatura sentado (cm)')),
                ('tricipital_fold', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Dobra tricipital (mm)')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='energycalc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_energcalc', to='patient.EnergyCalc', verbose_name='Calculos Energéticos'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation', to='patient.Patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patology',
            field=models.ManyToManyField(related_name='consultation_patology', to='patient.Patology', verbose_name='Patologia'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='skinfold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_skinfold', to='patient.SkinFold', verbose_name='Dobras Corporais'),
        ),
    ]
