# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='family_history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Histórico Familiar'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações gerais'),
        ),
    ]
