# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energycalc',
            name='height',
        ),
        migrations.RemoveField(
            model_name='energycalc',
            name='lean_mass',
        ),
        migrations.RemoveField(
            model_name='energycalc',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='skinfold',
            name='seated_height',
        ),
        migrations.AddField(
            model_name='consultation',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='energycalc',
            name='knee_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Altura do Joelho (cm)'),
        ),
    ]
