# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='family_history',
            field=models.CharField(blank=True, default='N/a', max_length=255, verbose_name='Histórico Familiar'),
            preserve_default=False,
        ),
    ]
