# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='energycalc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_energcalc', to='patient.EnergyCalc', verbose_name='Calculos Energ\xe9ticos'),
            preserve_default=False,
        ),
    ]
