# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='bone_diameter',
            new_name='bonediameter',
        ),
    ]
