# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidance',
            name='analysis',
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='analysis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_guidance', to='patient.Guidance', verbose_name='Orientação'),
            preserve_default=False,
        ),
    ]
