# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='nutrients',
            field=models.CharField(choices=[('OMS2008', 'OMS 2008'), ('DRI2002', 'DRI 2002/2005')], default='OMS2008', max_length=30, verbose_name='Adequação de Nutrientes'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.CharField(choices=[('1.0', 'Repouso'), ('1.5', 'Muito Leve'), ('2.5', 'Leve'), ('5.0', 'Moderada'), ('7.0', 'Intensa'), ('1.2', 'Acamado'), ('1.25', 'Acamado + móvel'), ('1.3', 'Ambulante')], default='1.5', max_length=30, null=True, verbose_name='Fator de Atividade'),
        ),
    ]
