# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodycircunference',
            old_name='distal_tigh_circ',
            new_name='distal_thigh_circ',
        ),
        migrations.RenameField(
            model_name='bodycircunference',
            old_name='medial_tigh_circ',
            new_name='medial_thigh_circ',
        ),
    ]
