# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_consultation_energycalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinFold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Peso (kg)')),
            ],
        ),
    ]
