# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180124_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Fator de Atividade')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Formula')),
            ],
        ),
    ]
