# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20171108_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='drugs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fármacos'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='evaluation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='feed_preferences',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferências Alimentares'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='life_style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estilo de vida'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prognostic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prognóstico'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fator de Atividade'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='calc_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Cálculo'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='mbr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taxa Metabólica Basal'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='met_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Método MET'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='tee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gasto Energético Total'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='weight_program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Programa de Peso'),
        ),
    ]
