# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180219_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação sobre o paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ocupation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Ocupação'),
        ),
    ]
