# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20171205_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodanalysis',
            old_name='analysis',
            new_name='guidance',
        ),
    ]
