# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_formula_formulavalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='patient.FormulaValue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='formula',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='patient.Formula'),
            preserve_default=False,
        ),
    ]
