# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180219_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(choices=[('BRANCO(A)', 'Branco(a)'), ('NEGRO(A)', 'Negro(a)'), ('INDÍGENA(A)', 'Indígeno(a)'), ('PARDO(A)', 'Pardo(a)'), ('MULATO(A)', 'Mulato(a)'), ('OUTRO', 'Outro')], default=None, max_length=10, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('CASADO(A)', 'Casado(a)'), ('SOLTEIRO(A)', 'Solteiro(a)'), ('SEPARADO(A)', 'Separado(a)'), ('VIUVO(A)', 'Viuvo(a)'), ('DIVORCIADO(A)', 'Divorciado(a)')], default='SOLTEIRO(A)', max_length=10, null=True, verbose_name='Estado Cívil'),
        ),
    ]
