# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('patient', '0003_auto_20171205_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceAux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('message', models.CharField(max_length=200, verbose_name='Mensagem')),
                ('show', models.BooleanField(verbose_name='Exibir?')),
            ],
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='abreviation_list',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='ac_folic',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='ac_oxalic',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='antioxidant',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='chronic_gastritis',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='chronic_hepatitis',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='chronic_pancreatitis',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='constipation',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='diarrhea',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='epilepsy',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='flatulent',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='functional',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='gout',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='hypertriglyceridemia',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='intestinal_inflammation',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='lactose_intolerance',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='laxative',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='megaesuffer',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='obstipating',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='osteoporosis',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='parkinson',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='peptic_ulcer',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='phosphor',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='renal_insufficiency_chronic',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='sulfur',
        ),
        migrations.RemoveField(
            model_name='guidance',
            name='trans_fat',
        ),
        migrations.AddField(
            model_name='guidance',
            name='description',
            field=models.CharField(default=None, max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidance',
            name='message',
            field=models.CharField(default=None, max_length=200, verbose_name='Mensagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidance',
            name='nutritionist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guidance_nutritionist', to='account.Nutritionist', verbose_name='Nutricionista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidance',
            name='show',
            field=models.BooleanField(default=None, verbose_name='Exibir?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='guidanceaux',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_guidanceaux', to='patient.GuidanceAux', verbose_name='OrientaçãoAux'),
            preserve_default=False,
        ),
    ]
