# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_skinfold'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='skinfold',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_skinfold', to='patient.SkinFold', verbose_name='Dobras Corporais'),
            preserve_default=False,
        ),
    ]
