# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20171203_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biochemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
        ),
        migrations.RemoveField(
            model_name='biochemicalexam',
            name='description',
        ),
        migrations.AddField(
            model_name='biochemicalexam',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value_biochemical', to='patient.Biochemical', verbose_name='Condição'),
            preserve_default=False,
        ),
    ]
