# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20171203_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biochemicalexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_biochemical', to='patient.Biochemical', verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='biochemical',
        ),
        migrations.AddField(
            model_name='consultation',
            name='biochemical',
            field=models.ManyToManyField(related_name='consultation_biochemical', to='patient.BiochemicalExam', verbose_name='Exame Bioquímico'),
        ),
    ]
