# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20171118_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patology',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patology',
            field=models.ManyToManyField(blank=True, null=True, related_name='consultation_patology', to='patient.Patology', verbose_name='Patologia'),
        ),
        migrations.AlterField(
            model_name='patology',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Patologia'),
        ),
    ]
