# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20180209_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.FormulaValue'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='formula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Formula'),
        ),
        migrations.AlterField(
            model_name='formulavalue',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_formula', to='patient.Formula', verbose_name='Fator de Atividade'),
        ),
    ]
