# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_consultation_skinfold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='file',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='formula',
            field=models.CharField(blank=True, choices=[('HARRIS-BENEDICT(1919)', 'Harris-Benedict(1919)'), ('HARRIS-BENEDICT(1984)', 'Harris-Benedict(1984)'), ('CUNNINGHAN(1996)', 'Cunninghan(1996)')], default=None, max_length=30, null=True, verbose_name='F\xf3rmula'),
        ),
    ]
