# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20180209_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.FormulaValue', verbose_name='Fator de Atividade'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='calc_title',
            field=models.CharField(blank=True, default='Calculo padrão', max_length=255, null=True, verbose_name='Título do Cálculo'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Formula', verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='formulavalue',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_formula', to='patient.Formula', verbose_name='Formula'),
        ),
    ]
