# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_uploadguidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_nutritionist', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista'),
        ),
    ]
