# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20171203_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='biochemical',
        ),
        migrations.AddField(
            model_name='consultation',
            name='biochemical',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_biochemical', to='patient.BiochemicalExam', verbose_name='Exame Bioquímico'),
            preserve_default=False,
        ),
    ]
