# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20171030_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='energycalc',
            name='activity_factor',
            field=models.CharField(default=None, max_length=255, verbose_name='Fator de Atividade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='calc_title',
            field=models.CharField(max_length=255, verbose_name='T\xedtulo do C\xe1lculo'),
        ),
    ]
