# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20171203_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='biochemical',
        ),
        migrations.AddField(
            model_name='biochemicalexam',
            name='consultation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_biochemical', to='patient.Consultation', verbose_name='Exame Bioquímico'),
            preserve_default=False,
        ),
    ]
