# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20171118_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patology',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patology',
            field=models.ManyToManyField(blank=True, null=True, related_name='consultation_patology', to='patient.Patology', verbose_name='Patologia'),
        ),
    ]
