# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20171118_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patology',
            field=models.ManyToManyField(blank=True, related_name='consultation_patology', to='patient.Patology', verbose_name='Patologia'),
        ),
    ]
