# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20171205_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidanceaux',
            old_name='description2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='guidanceaux',
            old_name='message2',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='guidanceaux',
            old_name='show2',
            new_name='show',
        ),
    ]
