# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20171102_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinfold',
            name='skin_fold',
        ),
        migrations.AlterField(
            model_name='skinfold',
            name='body_mass',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Massa Corporal (kg)'),
        ),
        migrations.AlterField(
            model_name='skinfold',
            name='seated_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Estatura sentado (cm)'),
        ),
        migrations.AlterField(
            model_name='skinfold',
            name='tricipital_fold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Dobra tricipital (mm)'),
        ),
    ]
