# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20171118_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energycalc',
            name='met_method',
        ),
        migrations.RemoveField(
            model_name='energycalc',
            name='weight_program',
        ),
    ]
