# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20171119_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Fator de Atividade'),
        ),
    ]
