# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20171206_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodanalysis',
            name='guidance',
        ),
        migrations.AddField(
            model_name='foodanalysis',
            name='guidance',
            field=models.ManyToManyField(related_name='analysis_guidance', to='patient.Guidance', verbose_name='Orientação'),
        ),
        migrations.AlterField(
            model_name='foodanalysis',
            name='guidanceaux',
            field=models.ManyToManyField(related_name='analysis_guidanceaux', to='patient.GuidanceAux', verbose_name='Orientação pré-definida'),
        ),
    ]
