# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20171119_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.DecimalField(choices=[('Sedentário', 1.2), ('Exercício Leve', 1.375), ('Exercício Moderado', 1.55), ('Exercício Pesado', 1.725), ('Exercício Muito Pesado', 1.9)], decimal_places=3, default='Sedentário', max_digits=8, verbose_name='Fator de Atividade'),
        ),
        migrations.AlterField(
            model_name='energycalc',
            name='formula',
            field=models.CharField(choices=[('HARRIS-BENEDICT(1919)', 'Harris-Benedict(1919)'), ('HARRIS-BENEDICT(1984)', 'Harris-Benedict(1984)'), ('CUNNINGHAN(1996)', 'Cunninghan(1996)')], default='HARRIS-BENEDICT(1919)', max_length=30, null=True, verbose_name='Fórmula'),
        ),
    ]
