# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20171207_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodanalysis',
            name='guidanceaux',
        ),
        migrations.DeleteModel(
            name='GuidanceAux',
        ),
    ]
