# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0014_auto_20171211_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidance',
            name='nutritionist',
        ),
        migrations.AddField(
            model_name='guidance',
            name='nut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guidance_nut', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista'),
            preserve_default=False,
        ),
    ]
