# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20171120_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycalc',
            name='activity_factor',
            field=models.CharField(choices=[('1.2', 'Sedentário'), ('1.375', 'Exercício Leve'), ('1.55', 'Exercício Moderado'), ('1.725', 'Exercício Pesado'), ('1.9', 'Exercício Muito Pesado')], default='1.2', max_length=30, null=True, verbose_name='Fórmula'),
        ),
    ]
