# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20171212_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='patology',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='supplement',
            field=models.ManyToManyField(blank=True, related_name='consultation_supplement', to='patient.Supplement', verbose_name='Suplemento'),
        ),
    ]
