# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20171216_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitamin', models.CharField(blank=True, choices=[('Vitamina A', 'Vitamina A'), ('Vitamina B', 'Vitamina B'), ('Vitamina C', 'Vitamina C')], default='Vitamina A', max_length=30, null=True, verbose_name='Fator de Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitamin',
            field=models.ManyToManyField(blank=True, related_name='consultation_vitamin', to='patient.Vitamin', verbose_name='Deficiência Vitamínica'),
        ),
    ]
