# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20171216_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitamin',
            name='vitamin',
        ),
        migrations.AddField(
            model_name='vitamin',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='vitamin',
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitamin',
            field=models.ManyToManyField(blank=True, related_name='consultation_vitamin', to='patient.Vitamin', verbose_name='Deficiência Vitamínica'),
        ),
    ]
