# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
