# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_address', to='account.Address', verbose_name='Endereço'),
        ),
    ]
