# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='brand',
            field=models.FileField(blank=True, null=True, upload_to='upload/brand', verbose_name='Logomarca (opcional)'),
        ),
    ]
