# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171129_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'permissions': (('can_list', 'Can list Nutritionist'), ('can_edit', 'Can edit Nutritionist'), ('can_create_nut', 'Can create Nutritionist'), ('can_delete', 'Can delete Nutritionist'))},
        ),
    ]
