# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171129_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
