# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171129_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionist',
            options={'permissions': (('can_create_nut', 'Can create NutritionistN'),)},
        ),
    ]
